### PR TITLE
SQLAlchemy JSON support

### PR DESCRIPTION
**Pull request by Ckk3**
## Description

This PR introduces native SQLAlchemy JSON conversion support. While it's unclear whether this is an actual issue or a deliberate design choice to exclude scalar types, I've made the necessary changes to enhance the functionality.

Resuming the changes, I've added `{sqlalchemy.JSON: strawberry.scalars.JSON}` in  `_default_sqlalchemy_type_to_strawberry_type_map`.

I'd like to extend my gratitude to @wisdomG for their assistance with Issue #22 .

Additionally, please note that some tests required adjustments due to automatic changes introduced by pre-commit. I am using devcontainers and followed all guides in [CONTRIBUTING.md](https://github.com/strawberry-graphql/.github/blob/a51071d3d64134a58d8355920f50efa28ec3a780/.github/CONTRIBUTING.md) for this development.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

*  #22 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by TimDumol** [comment]
> ## Description
> This PR introduces native SQLAlchemy JSON conversion support. While it's unclear whether this is an actual issue or a deliberate design choice to exclude scalar types, I've made the necessary changes to enhance the functionality.
> 
> Resuming the changes, I've added `{sqlalchemy.JSON: strawberry.scalars.JSON}` in `_default_sqlalchemy_type_to_strawberry_type_map`.
> 
> I'd like to extend my gratitude to @wisdomG for their assistance with Issue #22 .
> 
> Additionally, please note that some tests required adjustments due to automatic changes introduced by pre-commit. I am using devcontainers and followed all guides in [CONTRIBUTING.md](https://github.com/strawberry-graphql/.github/blob/a51071d3d64134a58d8355920f50efa28ec3a780/.github/CONTRIBUTING.md) for this development.
> 
> ## Types of Changes
> * [ ]  Core
> * [ ]  Bugfix
> * [x]  New feature
> * [ ]  Enhancement/optimization
> * [x]  Documentation
> 
> ## Issues Fixed or Closed by This PR
> * [Unsupported column type: `JSON` #22](https://github.com/strawberry-graphql/strawberry-sqlalchemy/issues/22)
> 
> ## Checklist
> * [x]  My code follows the code style of this project.
> * [x]  My change requires a change to the documentation.
> * [x]  I have updated the documentation accordingly.
> * [x]  I have read the CONTRIBUTING document.
> * [x]  I have added tests to cover my changes.
> * [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).

FWIW the reason why JSON was not originally included when I first wrote the library was because Strawberry didn't have a built-in JSON scalar type at that time, and not as a specific design decision

**Comment by Ckk3** [comment]
I understand, please let me know if the code needs any corrections, I'm available!

**Comment by Ckk3** [comment]
> > ## Description
> > This PR introduces native SQLAlchemy JSON conversion support. While it's unclear whether this is an actual issue or a deliberate design choice to exclude scalar types, I've made the necessary changes to enhance the functionality.
> > Resuming the changes, I've added `{sqlalchemy.JSON: strawberry.scalars.JSON}` in `_default_sqlalchemy_type_to_strawberry_type_map`.
> > I'd like to extend my gratitude to @wisdomG for their assistance with Issue #22 .
> > Additionally, please note that some tests required adjustments due to automatic changes introduced by pre-commit. I am using devcontainers and followed all guides in [CONTRIBUTING.md](https://github.com/strawberry-graphql/.github/blob/a51071d3d64134a58d8355920f50efa28ec3a780/.github/CONTRIBUTING.md) for this development.
> > ## Types of Changes
> > 
> > * [ ]   Core
> > * [ ]   Bugfix
> > * [x]   New feature
> > * [ ]   Enhancement/optimization
> > * [x]   Documentation
> > 
> > ## Issues Fixed or Closed by This PR
> > 
> > * [Unsupported column type: `JSON` #22](https://github.com/strawberry-graphql/strawberry-sqlalchemy/issues/22)
> > 
> > ## Checklist
> > 
> > * [x]   My code follows the code style of this project.
> > * [x]   My change requires a change to the documentation.
> > * [x]   I have updated the documentation accordingly.
> > * [x]   I have read the CONTRIBUTING document.
> > * [x]   I have added tests to cover my changes.
> > * [x]   I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> 
> FWIW the reason why JSON was not originally included when I first wrote the library was because Strawberry didn't have a built-in JSON scalar type at that time, and not as a specific design decision

Ok I understand, please let me know if the code needs any corrections, I'm available!

**Review by TimDumol — APPROVED** [review]
Looks ok to me

**Comment by Ckk3** [comment]
Resolved conflicts with main.

**Review by patrick91 — APPROVED** [review]
Looks great! thanks :D

**Review by patrick91 — APPROVED** [review]
Looks great! thanks :D

**Pull request merged**
