### PR TITLE
Refactor tests to use pytest.fixtures

### PR DESCRIPTION
**Pull request by Ckk3**
## Description

I refactored a few tests to utilize [pytest fixtures](https://docs.pytest.org/en/6.2.x/fixture.html). I noticed there were some 'TODO' comments in the tests, so I made the necessary changes.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* There's no Issues for this

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by patrick91 — APPROVED** [review]
Looks great! I'll leave it to @mattalbr to do a final check and merge 😊

**Comment by Ckk3** [comment]
> Looks great! I'll leave it to @mattalbr to do a final check and merge 😊

Thanks!

**Review by mattalbr — APPROVED** [review]
Nice, thanks!

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Pull request merged**
