### PR TITLE
update imports for strawberry 0.236.0

### PR DESCRIPTION
**Pull request by novag**
## Description

strawberry 0.236.0 changed the code structure which requires adjusting the imports.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

## Summary by Sourcery

This pull request updates the import paths in the `relay.py` file to be compatible with the changes in the code structure of strawberry 0.236.0, ensuring the project remains functional with the latest version.

- **Bug Fixes**:
    - Updated import paths to align with the new code structure introduced in strawberry 0.236.0.

### CODE REVIEW

**Comment by botberry** [comment]
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)

**Comment by patrick91** [comment]
I'll check this this week 😊 not sure what happened with the CI :D

**Comment by bperkins24** [comment]
Any update here?  It would be great to merge this in to unblock strawberry updates.  Happy to contribute somehow.

**Comment by Ckk3** [comment]
Hi, @novag 
Today I joined the Strawberry team as the maintainer for the SQLAlchemy integration. I’ve already started reviewing your code and investigating the issues with our CI.
Thank you for your contributions!

**Comment by Ckk3** [comment]
Hi, @novag , we are fixed the CI can you please update your branch from main?
Also, I think we missing the new version inside the `poetry.lock` file, can you update this too?

**Comment by Ckk3** [comment]
Thanks, @novag , please fix the failed tests when you can 😉

**Comment by Ckk3** [comment]
Just to make your job a little more fast, I've checked that you cax fix by just changing `_fields` to `fields` ([since StrawberryObjectDefinition has been changed](https://github.com/strawberry-graphql/strawberry/pull/3202))
image

I've tested this locally and worked on both failing tests

**Comment by novag** [comment]
Yes, thanks. I'm trying to determine what has changed that's now preventing the linter from inferring the lambda type.

**Comment by Ckk3** [comment]
Fixes #189

**Comment by Ckk3** [comment]
Hi @novag, I hope the investigation is going well! It’s been a week since we last discussed it. What do you think about pushing the current changes, especially to the tests, to see if the link tests are still failing? Let me know if you need any help!

**Comment by Ckk3** [comment]
@novag I noticed that the CI failed again on the lint check, but there's also a new error that has surfaced. It seems related to the new Ubuntu LTS (benchmark) and the Python environment (test matrix generation). I'll investigate further on another PR.

**Comment by Ckk3** [comment]
Hi, @novag , the CI fix is already on main, please update your branch when you can.

**Comment by novag** [comment]
@Ckk3 Thanks for fixing the CI! I am currently very limited in time, however I will have another look at the linter error today or tomorrow.

**Comment by bperkins24** [comment]
Hi @novag.  It would be great to get this done.  There are features in newer versions of strawberry that are very useful for my firm and we are blocked on using them until this is resolved.

**Comment by novag** [comment]
mypy fails at line 213 in `src/strawberry_sqlalchemy_mapper/field.py` because it cannot infer the type of the lambda expression. Although I don't think there's anything wrong here, I have not yet been able to find out why this check would have been successful before updating to strawberry 0.236.0. `field.py` is also sprinkled with `# type: ignore` comments. If that's finde for @Ckk3 we can just add one after the lambda expression.

If anyone is more familiar with mypy, I would appreciate any input.

**Comment by Ckk3** [comment]
I like this option,  what you guys think @patrick91 @bellini666 @TimDumol ?

**Comment by bellini666** [comment]
> I like this option, what you guys think @patrick91 @bellini666 @TimDumol ?

I think it is fine to ignore that specific error, even more because it is not actually related to this PR :)

**Review by Ckk3 — APPROVED** [review]

**Review by bellini666 — APPROVED** [review]

**Comment by botberry** [comment]
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥

**Comment by Ckk3** [comment]
Thanks @novag !

**Pull request merged**
